name: CI Pipeline

on:
  push: # DÃ©clenche le workflow sur le push de TOUTES les branches
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: ci-check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Ajuste si besoin (16.x, 20.x, etc.)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the project (TypeScript)
        run: npm run build

      - name: Run Jest tests
        run: npm test
